<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LE1481" ignored="1" name="Default test(failed)" tests="2" failures="2" timestamp="2020-07-06T06:49:10 IST" time="0.044" errors="0">
  <testcase name="test3" time="0.007" classname="Scripts.Retry_TestNG">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at Scripts.Retry_TestNG.test3(Retry_TestNG.java:23)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.001" classname="Scripts.Retry_TestNG">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Scripts.Retry_TestNG.test2(Retry_TestNG.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="Scripts.Retry_TestNG">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
